### ISSUE TITLE
 The calling function cannot get the secretKey exported from the called function

### ISSUE THREAD

**Issue by buyobuyo404** [open-quantum-safe/liboqs-go#11]
The calling function cannot get the private key exported from the called function.
Bellow are my calling function (TestGenerateKeyPQC) and the called function(GenerateKeyPQC)，**and I want to get the secretKey through GenerateKeyPQC**，however, when I execute TestGenerateKeyPQC，I can not gain the secretKey.
```
func TestGenerateKeyPQC(t *testing.T) {
	sigName := "Dilithium2"
	sk := GenerateKeyPQC(sigName)
	fmt.Println("sk2: ", sk)
}
```

```
func GenerateKeyPQC(sigName string) []byte {
	signer := oqs.Signature{}
	defer signer.Clean() // clean up even in case of panic

	if err := signer.Init(sigName, nil); err != nil {
		log.Fatal(err)
	}

	signer.GenerateKeyPair()
	sk := signer.ExportSecretKey()
	fmt.Println("sk: ", sk)
	return sk
}
```
here is the result, if anyone know what is wrong with the code, please tell me, i am really appreciate.
![Snipaste_2022-02-03_17-25-43](https://user-images.githubusercontent.com/78010512/152316355-e64a6b7e-d4f5-480c-8d86-aa2798ff6c21.png)

**Comment by vsoftco** [comment]
In the line `sk := signer.ExportSecretKey()`, the secret key is not copied, but simply its reference count increased. You then return it (which, under the hood, is still a reference to the secret key buffer, and not a copy). However, at the exit of the function, the `signer` object is destroyed (and, by design, this cleans the hot memory, including the secret key buffer). So, at the end of the day, the secret key you're referring to has been all zeroed.

You need to make a copy of the secret key before returning. https://gosamples.dev/copy-slice/
