### ISSUE TITLE
Is there a method to display the public key of signatures?

### ISSUE THREAD

**Issue by JannisFengler** [open-quantum-safe/liboqs-go#18]
There are 2 ways to init the signatures. One is to initiate with
 ```signer.Init(sigName, nil)``` 
After that, a keypair can be generated with 
```signer.GenerateKeyPair()``` 
which returns the public key. 

The second way is to initiate with: 
```signer.Init(sigName, secretKeyBytes)```

This function doesn't return a public key. I also didn't find a function like:
```signer.publicKey()```

Is there a best practice for extracting the public key? It would be great if this function would be part of the liboqs-go library.

**Comment by dstebila** [comment]
No, there's no method for extracting the public key from the signature object, since the signature object may not know the public key due to being initalized via `signer.Init(sigName, secretKeyBytes)`.  Note that being initialized with the secret key does not necessarily imply one can derive the public key, since there may not be a one-to-one mapping from secret keys to public keys.
